export const ADD_INGREDIENT_TO_CONSTRUCTOR:'ADD_INGREDIENT_TO_CONSTRUCTOR' = 'ADD_INGREDIENT_TO_CONSTRUCTOR';
export const DELETE_FROM_CONSTRUCTOR: 'DELETE_FROM_CONSTRUCTOR' = 'DELETE_FROM_CONSTRUCTOR';
export const CHANGE_INGREDIENTS_ORDER: 'CHANGE_INGREDIENTS_ORDER' = 'CHANGE_INGREDIENTS_ORDER';
export const RESET_CONSTRUCTOR: 'RESET_CONSTRUCTOR' = 'RESET_CONSTRUCTOR';

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_ERROR: 'GET_INGREDIENTS_ERROR' = 'GET_INGREDIENTS_ERROR';
export const SET_INGREDIENT_DETAILS: 'SET_INGREDIENT_DETAILS' = 'SET_INGREDIENT_DETAILS';

export const GET_ORDER_NUMBER_REQUEST: 'GET_ORDER_NUMBER_REQUEST' = 'GET_ORDER_NUMBER_REQUEST';
export const GET_ORDER_NUMBER_SUCCESS: 'GET_ORDER_NUMBER_SUCCESS' = 'GET_ORDER_NUMBER_SUCCESS';
export const GET_ORDER_NUMBER_ERROR: 'GET_ORDER_NUMBER_ERROR' = 'GET_ORDER_NUMBER_ERROR';

export const GET_ORDER_CARD_DETAILS_REQUEST: 'GET_ORDER_CARD_DETAILS_REQUEST' = 'GET_ORDER_CARD_DETAILS_REQUEST';
export const GET_ORDER_CARD_DETAILS_SUCCESS: 'GET_ORDER_CARD_DETAILS_SUCCESS' = 'GET_ORDER_CARD_DETAILS_SUCCESS';
export const GET_ORDER_CARD_DETAILS_ERROR: 'GET_ORDER_CARD_DETAILS_ERROR' = 'GET_ORDER_CARD_DETAILS_ERROR'; 

export const GET_USER_DATA_REQUEST: 'GET_USER_DATA_REQUEST' = 'GET_USER_DATA_REQUEST';
export const GET_USER_REGISTER_SUCCESS: 'GET_USER_REGISTER_SUCCESS' = 'GET_USER_REGISTER_SUCCESS';
export const GET_USER_DATA_ERROR: 'GET_USER_DATA_ERROR' = 'GET_USER_DATA_ERROR';
export const GET_USER_LOGIN_SUCCESS: 'GET_USER_LOGIN_SUCCESS' = 'GET_USER_LOGIN_SUCCESS';
export const GET_USER_FORGOT_PASSWORD_SUCCESS: 'GET_USER_FORGOT_PASSWORD_SUCCESS' = 'GET_USER_FORGOT_PASSWORD_SUCCESS';
export const GET_USER_RESET_PASSWORD_SUCCESS: 'GET_USER_RESET_PASSWORD_SUCCESS' = 'GET_USER_RESET_PASSWORD_SUCCESS';
export const GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS' = 'GET_USER_INFO_SUCCESS';
export const GET_USER_REFRESH_TOKEN_SUCCESS: 'GET_USER_REFRESH_TOKEN_SUCCESS' = 'GET_USER_REFRESH_TOKEN_SUCCESS';
export const GET_USER_INFO_UPDATE_SUCCESS: 'GET_USER_INFO_UPDATE_SUCCESS' = 'GET_USER_INFO_UPDATE_SUCCESS';
export const GET_USER_LOGOUT_SUCCESS: 'GET_USER_LOGOUT_SUCCESS' = 'GET_USER_LOGOUT_SUCCESS';

export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_START_PROFILE: 'WS_CONNECTION_START_PROFILE' ='WS_CONNECTION_START_PROFILE';
export const WS_CONNECTION_END: 'WS_CONNECTION_END' = 'WS_CONNECTION_END';
export const WS_PROFILE_CONNECTION_START: 'WS_PROFILE_CONNECTION_START' = 'WS_PROFILE_CONNECTION_START';

export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_GET_ORDERS: 'WS_GET_ORDERS' = 'WS_GET_ORDERS';